shared:
  image: node16

jobs:
  main:
    requires: [ ~commit, ~pr ]
    steps:
       - echo "commits or PRs against pipeline branch"
  alpha-prs:
    requires: [ ~pr:alpha ]
    steps:
       - echo "PR against alpha branch"
